
if PatchType(k) == 1
    % PATCH ON THE LEFT
    Screen('DrawTexture', window, ...
        PatchTex{freq_order_all{PatchType(k)}(WithinPatch1count(k))}, [], ...
        allRects1, ...
        angl_order_all{PatchType(k)}(WithinPatch1count(k)));
elseif PatchType(k) == 2
    % PATCH ON THE RIGHT
        Screen('DrawTexture', window, ...
        PatchTex{freq_order_all{PatchType(k)}(WithinPatch2count(k))}, [], ...
        allRects2, ...
        angl_order_all{PatchType(k)}(WithinPatch1count(k)));
end


